[deps]
AnythingLLMDocs = "333fe5f5-19c9-4863-8caf-c9193e7dba62"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
QuantumOptics = "6e0679c1-51ea-5a7c-ac74-d61b76210b0c"

[sources]
QuantumOptics = {path = "/workdir/dev/QuantumSavory/QuantumOptics.jl"}
